{% set version = "1.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-conquer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/conquer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/conquer/conquer_{{ version }}.tar.gz
  sha256: 14c28ab47b60c39696f34ee6fdd737bdcd2d28d05b3641c0e89960ab14a8bcd5

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-rcpparmadillo            # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-caret                    # [build_platform != target_platform]
    - r-matrixstats              # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - _openmp_mutex                # [linux]
    - llvm-openmp                  # [osx]
    - libblas
    - r-base
    - r-matrix
    - r-rcpp >=1.0.3
    - r-rcpparmadillo >=0.9.850.1.0
    - r-caret
    - r-matrixstats
  run:
    - _openmp_mutex                # [linux]
    - llvm-openmp                  # [osx]
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=1.0.3
    - r-rcpparmadillo >=0.9.850.1.0
    - r-caret
    - r-matrixstats

test:
  commands:
    - $R -e "library('conquer')"           # [not win]
    - "\"%R%\" -e \"library('conquer')\""  # [win]

about:
  home: https://github.com/XiaoouPan/conquer
  license: GPL-3.0-only
  summary: Fast and accurate convolution-type smoothed quantile regression. Implemented using Barzilai-Borwein gradient descent with a Huber regression warm start. Construct confidence intervals for regression coefficients using multiplier bootstrap.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: conquer
# Type: Package
# Title: Convolution-Type Smoothed Quantile Regression
# Version: 1.2.0
# Date: 2021-10-29
# Authors@R: c(person("Xuming", "He", email = "xmhe@umich.edu", role = "aut"), person("Xiaoou", "Pan", email = "xip024@ucsd.edu", role = c("aut", "cre")), person("Kean Ming", "Tan", email = "keanming@umich.edu", role = "aut"), person("Wen-Xin", "Zhou", email = "wez243@ucsd.edu", role = "aut"))
# Description: Estimation and inference for conditional linear quantile regression models using a convolution smoothed approach. In the low-dimensional setting, efficient gradient-based methods are employed for fitting both a single model and a regression process over a quantile range. Normal-based and (multiplier) bootstrap confidence intervals for all slope coefficients are constructed. In high dimensions, the conquer methods complemented with l_1-penalization and iteratively reweighted l_1-penalization are used to fit sparse models.
# Depends: R (>= 3.5.0)
# License: GPL-3
# Encoding: UTF-8
# URL: https://github.com/XiaoouPan/conquer
# SystemRequirements: C++11
# Imports: Rcpp (>= 1.0.3), Matrix, matrixStats, stats, caret
# LinkingTo: Rcpp, RcppArmadillo (>= 0.9.850.1.0)
# RoxygenNote: 7.1.1
# NeedsCompilation: yes
# Packaged: 2021-10-29 21:40:46 UTC; xopan
# Author: Xuming He [aut], Xiaoou Pan [aut, cre], Kean Ming Tan [aut], Wen-Xin Zhou [aut]
# Maintainer: Xiaoou Pan <xip024@ucsd.edu>
# Repository: CRAN
# Date/Publication: 2021-10-29 22:00:18 UTC
