{% set version = "1.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-conquer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/conquer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/conquer/conquer_{{ version }}.tar.gz
  sha256: a2c6155ed74af0e2a279145843ec5229ae2f3707aa25169ae030c520aa97deba

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-caret                      # [build_platform != target_platform]
    - r-matrixstats                # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
    - libblas
    - liblapack
    - r-base
    - r-caret
    - r-matrix
    - r-matrixstats
    - r-rcpp >=1.0.3
    - r-rcpparmadillo >=0.9.850.1.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-caret
    - r-matrix
    - r-matrixstats
    - r-rcpp >=1.0.3
    - r-rcpparmadillo >=0.9.850.1.0

test:
  commands:
    - $R -e "library('conquer')"           # [not win]
    - "\"%R%\" -e \"library('conquer')\""  # [win]

about:
  home: https://github.com/XiaoouPan/conquer
  license: GPL-3.0-only
  summary: Fast and accurate convolution-type smoothed quantile regression. Implemented using Barzilai-Borwein gradient descent with a Huber regression warm start. Construct confidence intervals for regression coefficients using multiplier bootstrap.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
